---
- name: Installer Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Démarrer et activer Nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Copier la page index personnalisée
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'
  notify: Redémarrer Nginx
